name: single-project-stage-deployment-loop
# Export solution from DEV environment
#  unpack it and prepare, commit and push a git branch with the changes

on:
  workflow_dispatch:
    
    
      
env:
#edit your values here
  ENVIRONMENT_URL: 'https://orga37e0bb9.crm.dynamics.com/'

permissions:
  contents: write
jobs:
  export-from-dev-demosolution:
    if: github.actor == 'hit3p48cy'
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        solution: [DemoSolution_2]
    
    # or you can say runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1

    environment:
      Dev
    
    steps:
    - uses: actions/checkout@v2.3.5
      with:
        lfs: true

    - name: Install Power Platform Tools
      uses: microsoft/powerplatform-actions/actions-install@v1
    
    - name: who-am-i action
      uses: microsoft/powerplatform-actions/who-am-i@v1
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{secrets.TENANT_ID}}


    - name: export-solution action
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
        environment-url: ${{env.ENVIRONMENT_URL}}
        app-id: ${{secrets.CLIENT_ID}}
        client-secret: ${{ secrets.PowerPlatformSPN }}
        tenant-id: ${{secrets.TENANT_ID}}
        solution-name: ${{ matrix.solution }}
        solution-output-file: ${{ github.event.repository.name}}/${{ matrix.solution }}_unmanaged.zip
        overwrite: true
        
    - name: unpack-solution action
      uses: microsoft/powerplatform-actions/unpack-solution@v1
      with:
        solution-file: ${{ github.event.repository.name}}/${{ matrix.solution }}_unmanaged.zip
        solution-folder: ${{ github.event.repository.name}}/${{ matrix.solution }}
        solution-type: 'Unmanaged'
        overwrite-files: true
        
    - name: export-managed-solution
      uses: microsoft/powerplatform-actions/export-solution@v1
      with:
            environment-url: ${{env.ENVIRONMENT_URL}}
            app-id: ${{secrets.CLIENT_ID}}
            client-secret: ${{ secrets.PowerPlatformSPN }}
            tenant-id: ${{secrets.TENANT_ID}}
            solution-name: ${{ matrix.solution }}
            solution-output-file: ${{ github.event.repository.name }}/${{ matrix.solution }}_managed.zip
            overwrite: true
            managed: true
    
    
    - name: Git Fetch and Commit 
      run: |
        git pull origin main
        git fetch --all  
        git config --global user.email "no-reply@github.com"
        git config --global user.name "GitHub Actions"
        git checkout main
        git add --all 
        git commit -m "Updates from the dev environment" --allow-empty
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        git push
